name: Release Docker images

on:
  schedule:
    - cron: '14 18 * * *' # UTC 18:14 (Local 02:14)
  push:
    tags: [ 'v*.*.*' ]
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install Compose
      uses: ndeloof/install-compose-action@v0.0.1
      with:
        version: v2.1.0 # defaults to 'latest'
        legacy: true    # will also install in PATH as `docker-compose`

    - name: Extract tag name
      if: startsWith(github.ref, 'refs/tags/')
      id: tag
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        script: |
          return context.payload.ref.replace(/\/refs\/tags\//, '');

    - uses: actions/checkout@v3

    - name: check
      run: |
        echo password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build NF's images
      if: startsWith(github.ref, 'refs/tags/')
      run: ./script/release.sh x86_64 ${{ steps.tag.outputs.result }}

    - name: Build NF's images
      if: github.ref == 'refs/heads/master'
      run: ./script/release.sh